config/routes.rb
Rails.application.routes.draw do


  get 'order/index'

  get 'order/show'

  get 'sessions/new'

  resources :users
  get 'cart/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'about/show'

  get 'passengers/create'

  get 'passengers/show'

  get 'flight/index'

  get 'flight/show'

  ######### Custom routes ##########

  resource :sessions

  root to: 'flight#index', as: 'flights'

  get 'about', to: 'about#show', as: 'about'

  get 'cart', to: 'cart#index', as: 'cart'

  post 'cart', to: 'cart#index'

  get 'index', to: 'flight#index'#, as: 'flights'

  get 'flights/:id', to: 'flight#show', as: 'flight', id: /\d+/

  get 'orders/index', to: 'order#index', as: 'orders'

  get 'orders', to: 'order#show', as: 'new_order'
  get 'orders/:id', to: 'order#show', as: 'order', id: /\d+/

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :flight_passengers
  has_many :flights, through: :flight_passengers
  has_many :users, through: :flight_passengers
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
    if session.has_key?(:user_id)
      #Display all user orders
      allOrderIds = User.where(id: session[:user_id]).first.flight_passengers.uniq.pluck(:order_id).uniq

      @allOrders = Order.find(allOrderIds).order(:created_at)

    else
      redirect_to new_sessions_path
    end
  end

  def show
    if session.has_key?(:user_id)

      @myOrder
      if params.has_key?(:id)
        #Display a users order
        @myOrder = Order.where(id: params[:id]).first

      else

        @myOrder = Order.create(subtotal: 0)
        @subTotal = 0.0
        session[:cart].each do |item|

          @newItem = FlightPassenger.create(quantity: item["quantity"], user_id: session[:user_id], order_id: @myOrder.id, flight_id: item["id"])

          @subTotal += Flight.where(id: item["id"]).first.price.to_f * item["quantity"].to_f
        end

        @myOrder.subtotal = @subTotal
        @myOrder.save

        session[:cart] = []
        #Create new user
      end

      @pst = 0.0
      @gst = 0.0
      @hst = 0.0

      @province = @myOrder.flight_passengers.first.user.province

      @pst = @province.pst
      @gst = @province.gst
      @hst = @province.hst

      @subTotal = @myOrder.subtotal.to_f
      @total = @subTotal

      @total = @subTotal + (@pst.to_f * @subTotal) + (@gst.to_f * @subTotal) + (@hst.to_f * @subTotal)
    else
      redirect_to new_sessions_path
    end
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
<%= render 'layouts/header' %>

<h1>All orders</h1>
<ul>
  <% @allOrders.each do |item| %>
      <li> subtotal: $<%= item.subtotal %> date ordered: <%= item.created_at %> <%= link_to 'View order', new_order_path %></li>
  <% end %>
</ul>

<%= render 'layouts/footer' %>

app/views/order/show.html.erb
<%= render 'layouts/header' %>
<h1>Your order</h1>
<ul>
    <% @myOrder.flight_passengers.each do |item| %>
        <li>
            <%= item.flight.name %> - $
            <%= item.flight.price%> x
            <%= item.quantity %> = $
            <%= item.flight.price * item.quantity %>
        </li>
    <% end %>

  <ul>
    <li>
        Subtotal: $<%= @myOrder.subtotal %>
    </li>
    <% if @hst.to_f > 0.0 %>
      <li>
          Hst (<%= @hst %>%): $<%= @myOrder.subtotal * @hst.to_f %>
      </li>
    <% end %>
    <% if @gst.to_f > 0.0%>
      <li>
        Gst (<%= @gst %>%): $<%= @myOrder.subtotal * @gst.to_f %>
      </li>
    <% end %>
    <% if @pst.to_f > 0.0%>
      <li>
        Pst (<%= @pst %>%): $<%= @myOrder.subtotal * @pst.to_f %>
      </li>
    <% end %>
    <li>
        Total: $<%= @total %>
    </li>
  </ul>
</ul>
<%= link_to 'All orders', orders_path %>

<%= render 'layouts/footer' %>